backend:
  name: git-gateway
  branch: main   # or master, depending on your repo

media_folder: "images/uploads"   # where uploaded files go
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
